### ISSUE TITLE
ActionVFX Converting properly to gif but not show up in library 

### ISSUE THREAD

**Issue by Dribliblu** [arunvfx/Ulaavi#1]
![image](https://user-images.githubusercontent.com/95220954/143859093-2e515a78-fdac-49a3-baef-bea738e99f69.png)
Hey Arun, 
Very hyped by Ulaavi, but when adding new stock footages from Action VFX, they seems to convert properly and they stay un loading state in the library (refrash make them disappear). 
Other stock are working as expected, only the one from Action VFX are buged.
Is it beacause they are in RGBA ProRes 4444 Quicktime file (which includes an alpha 
channel) ?
Thanks

**Comment by arunvfx** [comment]
Hey,
   Could you send me one sample file to test here. Here  it is working
fine. If there is any issue with codec or anything else, I can fix it here.
So I can improvise the tool.

Regards,
ARUN

**Comment by Dribliblu** [comment]
Here is an exemple file : https://fromsmash.com/ActionVFX-Sample
let me know if it's working on your side ;)

**Comment by arunvfx** [comment]
Then send me the data.json file

**Comment by Dribliblu** [comment]
https://fromsmash.com/datajson

**Comment by arunvfx** [comment]
It's been fixed. I ll send u the file

**Comment by Dribliblu** [comment]
Awesome, your tool is amazing, really impressive job. 
Thank you
